/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gedung;

import form.Utama;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import koneksi.Koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author arfani hidayat
 */
@SuppressWarnings("serial")
public class Gedung extends javax.swing.JFrame {

    public DefaultTableModel model;

    public Gedung() {
        initComponents();
        formatTabel();
        tampilGedung();
        jml();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldKode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldKet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonTambah = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jButtonSelesai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelGedung = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(680, 522));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gedung Mansaraya");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 650, 43));

        jLabel5.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel5.setText("Kode Gedung");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 108, -1, 30));

        jTextFieldKode.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextFieldKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldKodeKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 190, -1));

        jLabel3.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel3.setText("Nama Gedung");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        jTextFieldNama.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextFieldNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNamaKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 190, -1));

        jTextFieldKet.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextFieldKet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldKetKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 190, -1));

        jLabel4.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel4.setText("Keterangan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        jButtonTambah.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_index_add.png"))); // NOI18N
        jButtonTambah.setText("TAMBAH");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 110, -1));

        jButtonEdit.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_edit.png"))); // NOI18N
        jButtonEdit.setText("UBAH");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 110, -1));

        jButtonBatal.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_newdb.png"))); // NOI18N
        jButtonBatal.setText("BATAL");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 110, -1));

        jButtonHapus.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_drop.png"))); // NOI18N
        jButtonHapus.setText("HAPUS");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 110, -1));

        jButtonPrint.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_print.png"))); // NOI18N
        jButtonPrint.setText("CETAK");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 110, -1));

        jButtonSelesai.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonSelesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/s_success.png"))); // NOI18N
        jButtonSelesai.setText("SELESAI");
        jButtonSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 110, -1));

        tabelGedung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelGedung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelGedungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelGedung);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 440, 200));

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel2.setText("jumlah");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, 23));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelesaiActionPerformed
        new Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSelesaiActionPerformed

    private void tabelGedungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelGedungMouseClicked
        int t = tabelGedung.getSelectedRow();
        if (t == -1) {
            return;
        }

        String kode = (String) model.getValueAt(t, 0);
        jTextFieldKode.setText(kode);
        String nGedung = (String) model.getValueAt(t, 1);
        jTextFieldNama.setText(nGedung);
        String ket = (String) model.getValueAt(t, 2);
        jTextFieldKet.setText(ket);
    }//GEN-LAST:event_tabelGedungMouseClicked

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        kosong();
        ada = false;
        tabelGedung.clearSelection();
        jTextFieldKode.requestFocus();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        try {
            int tt = tabelGedung.getSelectedRow();
            if (tt != -1) {
                int t = tabelGedung.getSelectedRow();
                String kode = (String) model.getValueAt(t, 0);
                String nama = (String) model.getValueAt(t, 1);
                int h = JOptionPane.showConfirmDialog(null, "Hapus gedung \"" + nama + "\" dengan kode \"" + kode + "\" ?",
                        "Konfirmasi",
                        JOptionPane.YES_NO_OPTION);
                if (h == JOptionPane.YES_OPTION) {
                    hapus();
                    jButtonTambah.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Klik tombol hapus kembali setelah"
                        + " anda memilih data pada tabel yang akan dihapus!");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "pilih data terlebih dahulu\n" + e.getMessage());
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    boolean ada = false;
    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        //pemberitahuan kosong field
        if (jTextFieldKode.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi kode bangunan baru !");
            jTextFieldKode.requestFocus();
        } else if (jTextFieldNama.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi nama bangunan baru !");
            jTextFieldNama.requestFocus();
        } else {
            cekduplikat();
            if (ada == true) {
                jTextFieldKode.requestFocus();
            } else {
                insert();
            }
        }
        ada = false;
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        try {
            int tt = tabelGedung.getSelectedRow();
            if (tt != -1) {
                int t = tabelGedung.getSelectedRow();
                String kodeLama = (String) model.getValueAt(t, 0);
                String namaLama = (String) model.getValueAt(t, 1);
                String ketLama = (String) model.getValueAt(t, 2);
                String kode = jTextFieldKode.getText();
                String nama = jTextFieldNama.getText();
                String ket = jTextFieldKet.getText();
                if (kodeLama.equals(kode) && namaLama.equals(nama) && ketLama.equals(ket)) {
                    JOptionPane.showMessageDialog(rootPane, "Anda belum memodifikasi data!");
                    jTextFieldKode.requestFocus();
                } else {
                    int h = JOptionPane.showConfirmDialog(null, "Ubah data gedung ?",
                            "Konfirmasi",
                            JOptionPane.YES_NO_OPTION);
                    if (h == JOptionPane.YES_OPTION) {
                        update();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Klik tombol UBAH kembali setelah anda "
                        + "memilih data pada tabel dan memodifikasinya!");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "Error Edit \n" + e.getMessage());
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        try {
            String filename = "src/laporan/Gedung.jasper";

            Connection con = Koneksi.getkoneksi();
            File report = new File(filename);
            @SuppressWarnings("deprecation")
            JasperReport jsp = (JasperReport) JRLoader.loadObject(report.getPath());
            @SuppressWarnings("unchecked")
            JasperPrint jspprint = JasperFillManager.fillReport(jsp, null, con);
            JasperViewer.viewReport(jspprint, false);

            JasperViewer.setDefaultLookAndFeelDecorated(true);

        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, "Error cetak\n"
                    + "Pesan error : " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jTextFieldNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNamaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldKet.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldNamaKeyPressed

    private void jTextFieldKetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKetKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonTambah.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldKetKeyPressed

    private void jTextFieldKodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNama.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldKodeKeyPressed

    //
    public void update() {
        int t = tabelGedung.getSelectedRow();
        String kodeLama = (String) model.getValueAt(t, 0);
        String kode = jTextFieldKode.getText();
        String nama = jTextFieldNama.getText();
        String ket = jTextFieldKet.getText();
        try {
            Connection c = Koneksi.getkoneksi();
            Statement st = c.createStatement();

            String sql = "update gedung set "
                    + "kode_gedung='" + kode + "', "
                    + "nama_gedung='" + nama + "', "
                    + "keterangan ='" + ket + "' "
                    + "where kode_gedung='" + kodeLama + "'";
            try (PreparedStatement p = c.prepareStatement(sql)) {
                p.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            tampilGedung();
            jml();
            kosong();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error update data\n" + e.getMessage());
        }
    }

    //
    public void cekduplikat() {
        String kode = jTextFieldKode.getText();
        try {
            Connection c = Koneksi.getkoneksi();
            try (Statement s = c.createStatement()) {
                String sql = " select * from gedung";
                try (ResultSet r = s.executeQuery(sql)) {
                    while (r.next()) {
                        String b = r.getString("kode_gedung");
                        if (kode.equals(b)) {
                            JOptionPane.showMessageDialog(null, "Kode gedung sudah ada!");
                            ada = true;
                            break;
                        }
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error cek duplikat \n" + e.getMessage());
        }
    }

    //
    public void insert() {
        String kode = jTextFieldKode.getText();
        String nama = jTextFieldNama.getText();
        String ket = jTextFieldKet.getText();

        try {
            Connection c = Koneksi.getkoneksi();
            Statement st = c.createStatement();

            String sql = "insert into gedung set "
                    + "kode_gedung='" + kode + "', "
                    + "nama_gedung='" + nama + "', "
                    + "keterangan='" + ket + "'";
            try (PreparedStatement p = c.prepareStatement(sql)) {
                p.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "Gedung tersimpan");
            tampilGedung();
            jml();
            kosong();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error insert data\n" + e.getMessage());
        }
    }

    //
    public void hapus() {
        int t = tabelGedung.getSelectedRow();
        String kode = (String) model.getValueAt(t, 0);
        try {
            Connection c = Koneksi.getkoneksi();
            Statement st = c.createStatement();

            String sql = "delete from gedung where kode_gedung='" + kode + "'";
            try (PreparedStatement p = c.prepareStatement(sql)) {
                p.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "Data terhapus");
            tampilGedung();
            jml();
            kosong();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error hapus data\n" + e.getMessage());
        }
    }

    //
    public void kosong() {
        jTextFieldKode.setText(null);
        jTextFieldKet.setText(null);
        jTextFieldNama.setText(null);
    }

    public void jml() {
        int a = tabelGedung.getRowCount();
        jLabel2.setText("Jumlah Bangunan = " + String.valueOf(a));
    }

    //
    public void formatTabel() {
        model = new DefaultTableModel();

        tabelGedung.setModel(model);

        model.addColumn("Kode Gedung");
        model.addColumn("Nama Gedung");
        model.addColumn("Keterangan");
        TableColumn kol;
        tabelGedung.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        kol = tabelGedung.getColumnModel().getColumn(0);
        kol.setPreferredWidth(100);
        kol = tabelGedung.getColumnModel().getColumn(1);
        kol.setPreferredWidth(150);
        kol = tabelGedung.getColumnModel().getColumn(2);
        kol.setPreferredWidth(193);
    }

    //
    public void tampilGedung() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            Connection c = Koneksi.getkoneksi();
            Statement st = c.createStatement();

            String sql = "select * from gedung";
            try (ResultSet rs = st.executeQuery(sql)) {
                while (rs.next()) {
                    Object[] o = new Object[3];
                    o[0] = rs.getString("kode_gedung");
                    o[1] = rs.getString("nama_gedung");
                    o[2] = rs.getString("keterangan");

                    model.addRow(o);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error tampil gedung\n" + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Gedung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Gedung().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSelesai;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldKet;
    private javax.swing.JTextField jTextFieldKode;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTable tabelGedung;
    // End of variables declaration//GEN-END:variables
}
