package form;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

@SuppressWarnings("serial")
public class UbahUser extends javax.swing.JFrame {

    public UbahUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBatal = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonSimpan = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 102), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        jPanel1.setLayout(null);

        jButtonBatal.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/s_success.png"))); // NOI18N
        jButtonBatal.setText("SELESAI");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBatal);
        jButtonBatal.setBounds(150, 260, 105, 28);

        jPasswordField3.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField3KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField3);
        jPasswordField3.setBounds(30, 190, 152, 30);

        jLabel3.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel3.setText("Username baru");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 110, 110, 18);

        jLabel4.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 170, 70, 18);

        jTextFieldUser.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextFieldUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUserKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldUser);
        jTextFieldUser.setBounds(30, 130, 152, 30);

        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ubah Username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 23, 310, 46);

        jButtonSimpan.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_save.png"))); // NOI18N
        jButtonSimpan.setText("SIMPAN");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSimpan);
        jButtonSimpan.setBounds(30, 260, 105, 28);

        jCheckBox3.setFont(new java.awt.Font("Abyssinica SIL", 0, 10)); // NOI18N
        jCheckBox3.setText("Tampil");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(200, 190, 70, 24);

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Edit.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 0, 140, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        simpan();
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        new Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jPasswordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonSimpan.requestFocus();
        }
    }//GEN-LAST:event_jPasswordField3KeyPressed

    private void jTextFieldUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUserKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jPasswordField3.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldUserKeyPressed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if (jCheckBox3.isSelected()){
            jPasswordField3.setEchoChar((char) 0);
        }else{
            jPasswordField3.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    public void simpan() {
        @SuppressWarnings("deprecation")
        String oldP = jPasswordField3.getText();
        try {
            Connection c = Koneksi.getkoneksi();
            Statement s = c.createStatement();

            String sql = "select password from user";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                String b = r.getString("password");

                if (oldP.equals(b)) {
                    ganti();
                    kosong();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "password salah");
                    jPasswordField3.requestFocus();
                }
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error cek pass \n" + e.getMessage());
        }
    }

    //
    void kosong(){
        jTextFieldUser.setText(null);
        jPasswordField3.setText("");
    }

    public void ganti() {
        String user = jTextFieldUser.getText();
        @SuppressWarnings("deprecation")
        String pass = jPasswordField3.getText();

        try {
            Connection c = Koneksi.getkoneksi();
            Statement st = c.createStatement();

            String sql = "update user set username='" + user + "' "
                    + "where password='" + pass + "'";
            PreparedStatement p = c.prepareStatement(sql);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "username berhasil diubah");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error update user\n"
                    + "Pesan Error: "+e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UbahUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UbahUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
