
package form;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

@SuppressWarnings("serial")
public class UbahPass extends javax.swing.JFrame {
    public UbahPass() {
        initComponents();
        jLabel5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jButtonSimpan = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 102), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 102)));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 90, 70, 18);

        jLabel3.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel3.setText("Password baru");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 150, 110, 18);

        jLabel4.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel4.setText("Ulang password baru");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 210, 140, 18);

        jCheckBox1.setFont(new java.awt.Font("Abyssinica SIL", 0, 10)); // NOI18N
        jCheckBox1.setText("Tampil");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(210, 110, 70, 24);

        jCheckBox2.setFont(new java.awt.Font("Abyssinica SIL", 0, 10)); // NOI18N
        jCheckBox2.setText("Tampil");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(210, 170, 70, 24);

        jCheckBox3.setFont(new java.awt.Font("Abyssinica SIL", 0, 10)); // NOI18N
        jCheckBox3.setText("Tampil");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(210, 230, 70, 24);

        jPasswordField1.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(50, 110, 150, 30);

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Password tidak cocok");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 260, 150, 17);

        jButtonSimpan.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_save.png"))); // NOI18N
        jButtonSimpan.setText("SIMPAN");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSimpan);
        jButtonSimpan.setBounds(50, 300, 105, 28);

        jButtonBatal.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/s_success.png"))); // NOI18N
        jButtonBatal.setText("SELESAI");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBatal);
        jButtonBatal.setBounds(170, 300, 105, 28);

        jPasswordField2.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jPasswordField2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPasswordField2CaretUpdate(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(50, 170, 150, 30);

        jPasswordField3.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jPasswordField3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPasswordField3CaretUpdate(evt);
            }
        });
        jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField3KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField3);
        jPasswordField3.setBounds(50, 230, 151, 30);

        jLabel6.setFont(new java.awt.Font("Abyssinica SIL", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ubah Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 20, 310, 46);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Edit.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 0, 140, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        simpan();
        kosong();
        jLabel5.setVisible(false);
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        new Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    @SuppressWarnings("deprecation")
    private void jPasswordField3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPasswordField3CaretUpdate
        jLabel5.setVisible(true);
        
        if (jPasswordField3.getText().equals(jPasswordField2.getText())){
            jLabel5.setText("Password cocok");
            jLabel5.setForeground(Color.blue);
            jButtonSimpan.setEnabled(true);
        }else{
            jLabel5.setText("Password tidak cocok");
            jLabel5.setForeground(Color.red);
            jButtonSimpan.setEnabled(false);
        }
    }//GEN-LAST:event_jPasswordField3CaretUpdate

    @SuppressWarnings("deprecation")
    private void jPasswordField2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPasswordField2CaretUpdate
        if (jPasswordField3.getText().equals(jPasswordField2.getText())){
            jLabel5.setText("Password cocok");
            jLabel5.setForeground(Color.blue);
            jButtonSimpan.setEnabled(true);
        }else{
            jLabel5.setText("Password tidak cocok");
            jLabel5.setForeground(Color.red);
            jButtonSimpan.setEnabled(false);
        }
    }//GEN-LAST:event_jPasswordField2CaretUpdate

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()){
            jPasswordField1.setEchoChar((char) 0);
        }else{
         jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if (jCheckBox2.isSelected()){
            jPasswordField2.setEchoChar((char) 0);
        }else{
         jPasswordField2.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if (jCheckBox3.isSelected()){
            jPasswordField3.setEchoChar((char) 0);
        }else{
         jPasswordField3.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jPasswordField2.requestFocus();
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jPasswordField3.requestFocus();
        }
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jPasswordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField3KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButtonSimpan.requestFocus();
        }
    }//GEN-LAST:event_jPasswordField3KeyPressed
    //
    public void kosong(){
        jPasswordField1.setText(null);
        jPasswordField2.setText(null);
        jPasswordField3.setText(null);
    }
    public void simpan() {
        @SuppressWarnings("deprecation")
        String oldP = jPasswordField1.getText();
        try {
            Connection c = Koneksi.getkoneksi();
            Statement s = c.createStatement();

            String sql = "select * from user";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                String b = r.getString("password");

                if (oldP.equals(b)){
                    ganti();
                }else{
                    JOptionPane.showMessageDialog(null, "password salah");
                    jPasswordField1.requestFocus();
                }
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error cek pass \n" + e.getMessage());
        }
    }
    //
    public void ganti(){
        @SuppressWarnings("deprecation")
        String pass = jPasswordField2.getText();
        
        try {
            Connection c = Koneksi.getkoneksi();
            Statement st = c.createStatement();

            String sql = "update user set password='" + pass + "' ";
            PreparedStatement p = c.prepareStatement(sql);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "password berhasil diubah");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error update pass "+e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UbahPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UbahPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    // End of variables declaration//GEN-END:variables
}
