package formbarang;

import form.Utama;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import koneksi.Koneksi;

@SuppressWarnings("serial")
public class InputBarang extends javax.swing.JFrame {

    public DefaultTableModel model;

    public InputBarang() {
        initComponents();
        formatTabel();
        lebarkol();
        iComboR();
        keseluruhan();
        jml();
        kosong();
        jComboRuangan.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelKode = new javax.swing.JLabel();
        jComboRuangan = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextKode = new javax.swing.JTextField();
        jTextNamaBarang = new javax.swing.JTextField();
        jTextTahunPengadaan = new javax.swing.JTextField();
        jTextSfc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextJumlah = new javax.swing.JTextField();
        jTextKondisiTT = new javax.swing.JTextField();
        jTextKondisiRB = new javax.swing.JTextField();
        jTextKondisiRR = new javax.swing.JTextField();
        jTextKondisiB = new javax.swing.JTextField();
        jTextKet = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jButtonSimpan = new javax.swing.JButton();
        jButtonSimpan1 = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1130, 665));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Abyssinica SIL", 1, 36)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Input Barang");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1130, 40));

        jLabelKode.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N

        jComboRuangan.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jComboRuangan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "keseluruhan" }));
        jComboRuangan.setToolTipText("");
        jComboRuangan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboRuanganItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel10.setText("RUANGAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jComboRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabelKode, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboRuangan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 450, 30));

        jLabel9.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel9.setText("nama gedung");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 190, 30));

        jLabel8.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel8.setText("GEDUNG");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, 30));

        jLabel18.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel18.setText("Kode Barang");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, 30));

        jLabel3.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 30));

        jLabel13.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel13.setText("Tahun Pengadaan");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 30));

        jLabel4.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel4.setText("Spesifikasi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        jTextKode.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextKodeKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextKodeKeyPressed(evt);
            }
        });
        getContentPane().add(jTextKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 220, -1));

        jTextNamaBarang.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextNamaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNamaBarangKeyPressed(evt);
            }
        });
        getContentPane().add(jTextNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 220, -1));

        jTextTahunPengadaan.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextTahunPengadaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextTahunPengadaanKeyPressed(evt);
            }
        });
        getContentPane().add(jTextTahunPengadaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 220, -1));

        jTextSfc.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextSfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextSfcKeyPressed(evt);
            }
        });
        getContentPane().add(jTextSfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 220, -1));

        jLabel5.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 80, 30));

        jLabel6.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel6.setText("Kondisi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 80, 50));

        jLabel7.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel7.setText("Keterangan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 80, 30));

        jLabel14.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("b");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 25, -1));

        jLabel15.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("rr");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 25, -1));

        jLabel16.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("rb");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 25, -1));

        jLabel17.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("tt");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 25, -1));

        jTextJumlah.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextJumlahKeyPressed(evt);
            }
        });
        getContentPane().add(jTextJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 220, -1));

        jTextKondisiTT.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextKondisiTT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextKondisiTTKeyPressed(evt);
            }
        });
        getContentPane().add(jTextKondisiTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 25, -1));

        jTextKondisiRB.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextKondisiRB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextKondisiRBKeyPressed(evt);
            }
        });
        getContentPane().add(jTextKondisiRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 25, -1));

        jTextKondisiRR.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextKondisiRR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextKondisiRRKeyPressed(evt);
            }
        });
        getContentPane().add(jTextKondisiRR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 25, -1));

        jTextKondisiB.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextKondisiB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextKondisiBKeyPressed(evt);
            }
        });
        getContentPane().add(jTextKondisiB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 25, -1));

        jTextKet.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jTextKet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextKetKeyPressed(evt);
            }
        });
        getContentPane().add(jTextKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 220, -1));

        jLabel11.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("nama ruangan");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 920, 40));

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tabelbarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelbarang.setFocusable(false);
        tabelbarang.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelbarang);
        if (tabelbarang.getColumnModel().getColumnCount() > 0) {
            tabelbarang.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 1067, 190));

        jLabel12.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, -1, -1));

        jButtonSimpan.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_save.png"))); // NOI18N
        jButtonSimpan.setText("SIMPAN");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 110, -1));

        jButtonSimpan1.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonSimpan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/b_newdb.png"))); // NOI18N
        jButtonSimpan1.setText("BATAL");
        jButtonSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpan1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 110, -1));

        jButtonBatal.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButtonBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/s_success.png"))); // NOI18N
        jButtonBatal.setText("SELESAI");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 110, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        //pemberitahuan kosong field
        hitungkondisi();
        if (jTextKode.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "kode barang tidak boleh kosong !");
            jTextKode.requestFocus();
        } else if (jTextNamaBarang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "nama barang tidak boleh kosong !");
            jTextNamaBarang.requestFocus();
        } else if (jTextTahunPengadaan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "tahun pengadaan tidak boleh kosong !");
            jTextTahunPengadaan.requestFocus();
        } else if (jTextJumlah.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "jumlah barang tidak boleh kosong !");
            jTextJumlah.requestFocus();
        } else if (jTextKondisiB.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon isi field kondisi");
            jTextKondisiB.requestFocus(true);
        } else if (jTextKondisiRR.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon isi field kondisi");
            jTextKondisiRR.requestFocus(true);
        } else if (jTextKondisiRB.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon isi field kondisi");
            jTextKondisiRB.requestFocus(true);
        } else if (jTextKondisiTT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon isi field kondisi");
            jTextKondisiTT.requestFocus(true);
        } else if (kondisi == false) {
            JOptionPane.showMessageDialog(rootPane, "Jumlah barang dan kondisi barang tidak cocok !");
            jTextJumlah.requestFocus();
        } else {
            cekduplikat();
            if (ada == true) {
                jTextKode.requestFocus();
            } else {
                insert();
            }
        }
        kondisi = true;
    }//GEN-LAST:event_jButtonSimpanActionPerformed
    //
    boolean ada = false;

    public void cekduplikat() {
        String kBarang = jTextKode.getText();
        try {
            Connection c = Koneksi.getkoneksi();
            Statement s = c.createStatement();

            String sql = " select kode_barang from detailbarang";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                String b = r.getString("kode_barang");

                if (kBarang.equals(b)) {
                    JOptionPane.showMessageDialog(null, "Kode barang sudah ada\n"
                            + "Ganti kode barang");
                    ada = true;
                    break;
                }
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error duplikat \n" + e.getMessage());
        }
    }

    //
    public void insert() {
        String combo = jComboRuangan.getSelectedItem().toString();
        String kBarang = jTextKode.getText();
        String nBarang = jTextNamaBarang.getText();
        String tPengadaan = jTextTahunPengadaan.getText();
        String sfc = jTextSfc.getText();
        String jml = jTextJumlah.getText();
        String kondisiB = jTextKondisiB.getText();
        String kondisiRR = jTextKondisiRR.getText();
        String kondisiRB = jTextKondisiRB.getText();
        String kondisiTT = jTextKondisiTT.getText();
        String ket = jTextKet.getText();

        try {
            Connection c = Koneksi.getkoneksi();

            String sql = "insert into detailbarang set "
                    + "kode_barang='" + kBarang + "', "
                    + "nama_barang='" + nBarang + "', "
                    + "sfc='" + sfc + "', "
                    + "jumlah='" + jml + "', "
                    + "kondisi_b='" + kondisiB + "', "
                    + "kondisi_rr='" + kondisiRR + "', "
                    + "kondisi_rb='" + kondisiRB + "', "
                    + "kondisi_tt='" + kondisiTT + "', "
                    + "tahun_pengadaan='" + tPengadaan + "', "
                    + "keterangan='" + ket + "', "
                    + "ruanganfk='" + jLabelKode.getText() + "'";
            PreparedStatement p = c.prepareStatement(sql);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data barang tersimpan");
            tampilPerRuangan();
            jTextKode.requestFocus();
            jml();
            kosong();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error insert data :\n"
                    + "1. Pastikan anda sudah memilih ruangan!"
                    + e.getMessage());
        }
    }

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        new Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jComboRuanganItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboRuanganItemStateChanged
        try {
            String namaRuang = jComboRuangan.getSelectedItem().toString();
            Connection c = Koneksi.getkoneksi();
            Statement s = c.createStatement();

            String sql = " select * from ruangan where nama_ruangan='" + namaRuang + "'";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                String kodeRuangan = r.getString("kode_ruangan");
                jLabelKode.setText(kodeRuangan);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error masukkan kode \n" + e.getMessage());
        }
        jLabel11.setText(jComboRuangan.getSelectedItem().toString());
        iGedung();
        String a = jComboRuangan.getSelectedItem().toString();
        if (a.equals("keseluruhan")) {
            keseluruhan();
        } else {
            formatTabel();
            lebarkol();
            tampilPerRuangan();
        }
        jml();
    }//GEN-LAST:event_jComboRuanganItemStateChanged

    private void jTextNamaBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNamaBarangKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextTahunPengadaan.requestFocus();
        }
    }//GEN-LAST:event_jTextNamaBarangKeyPressed

    private void jTextJumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextJumlahKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextKondisiB.requestFocus();
        }
    }//GEN-LAST:event_jTextJumlahKeyPressed

    private void jTextKondisiBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextKondisiBKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextKondisiRR.requestFocus();
        }
    }//GEN-LAST:event_jTextKondisiBKeyPressed

    private void jTextKetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextKetKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonSimpan.requestFocus();
        }
    }//GEN-LAST:event_jTextKetKeyPressed

    private void jTextTahunPengadaanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTahunPengadaanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextSfc.requestFocus();
        }
    }//GEN-LAST:event_jTextTahunPengadaanKeyPressed

    private void jTextSfcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSfcKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextJumlah.requestFocus();
        }
    }//GEN-LAST:event_jTextSfcKeyPressed

    private void jTextKondisiRRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextKondisiRRKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextKondisiRB.requestFocus();
        }
    }//GEN-LAST:event_jTextKondisiRRKeyPressed

    private void jTextKondisiRBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextKondisiRBKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextKondisiTT.requestFocus();
        }
    }//GEN-LAST:event_jTextKondisiRBKeyPressed

    private void jTextKondisiTTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextKondisiTTKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextKet.requestFocus();
        }
    }//GEN-LAST:event_jTextKondisiTTKeyPressed

    private void jTextKodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextKodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextNamaBarang.requestFocus();
        }
    }//GEN-LAST:event_jTextKodeKeyPressed

    private void jTextKodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextKodeKeyTyped
        ada = false;
    }//GEN-LAST:event_jTextKodeKeyTyped

    private void jButtonSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpan1ActionPerformed
        kosong();
        jTextKode.requestFocus();
        tabelbarang.clearSelection();
    }//GEN-LAST:event_jButtonSimpan1ActionPerformed

    //
    Boolean kondisi = true;

    public void hitungkondisi() {
        try {
            int b = Integer.parseInt(jTextKondisiB.getText());
            int rr = Integer.parseInt(jTextKondisiRR.getText());
            int rb = Integer.parseInt(jTextKondisiRB.getText());
            int tt = Integer.parseInt(jTextKondisiTT.getText());
            int jml = Integer.parseInt(jTextJumlah.getText());
            int Hasil = b + rr + rb + tt;
            if (Hasil != jml) {
                kondisi = false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Pastikan anda memasukkan jumlah dan kondisi barang dengan angka valid! \n" + e.getMessage());
        }
    }

    //
    public void lebarkol() {
        TableColumn kol;
        tabelbarang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        kol = tabelbarang.getColumnModel().getColumn(0);
        kol.setPreferredWidth(128);
        kol = tabelbarang.getColumnModel().getColumn(1);
        kol.setPreferredWidth(128);
        kol = tabelbarang.getColumnModel().getColumn(2);
        kol.setPreferredWidth(200);
        kol = tabelbarang.getColumnModel().getColumn(3);
        kol.setPreferredWidth(70);
        kol = tabelbarang.getColumnModel().getColumn(4);
        kol.setPreferredWidth(100);
        kol = tabelbarang.getColumnModel().getColumn(5);
        kol.setPreferredWidth(50);
        kol = tabelbarang.getColumnModel().getColumn(6);
        kol.setPreferredWidth(60);
        kol = tabelbarang.getColumnModel().getColumn(7);
        kol.setPreferredWidth(60);
        kol = tabelbarang.getColumnModel().getColumn(8);
        kol.setPreferredWidth(60);
        kol = tabelbarang.getColumnModel().getColumn(9);
        kol.setPreferredWidth(60);
        kol = tabelbarang.getColumnModel().getColumn(10);
        kol.setPreferredWidth(150);
    }

    //
    public void jml() {
        int a = tabelbarang.getRowCount();
        jLabel12.setText("Jumlah barang = " + String.valueOf(a));
    }

    //
    public void formatTabel() {
        jLabel11.setText("keseluruhan");
        jLabel9.setText("\"pilih ruangan\"");
        //membuat format tabel
        model = new DefaultTableModel();

        tabelbarang.setModel(model);

        model.addColumn("Nama Ruangan");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Th Peng");
        model.addColumn("Sfc");
        model.addColumn("Jumlah");
        model.addColumn("Kond B");
        model.addColumn("Kond RR");
        model.addColumn("Kond RB");
        model.addColumn("Kond TT");
        model.addColumn("Keterangan");
    }

    //
    public void kosong() {
        jTextKode.setText("");
        jTextNamaBarang.setText("");
        jTextTahunPengadaan.setText("");
        jTextSfc.setText("");
        jTextJumlah.setText("1");
        jTextKondisiB.setText("0");
        jTextKondisiRR.setText("0");
        jTextKondisiRB.setText("0");
        jTextKondisiTT.setText("0");
        jTextKet.setText("");
    }

    //
    public void tampilPerRuangan() {
        String combo = jComboRuangan.getSelectedItem().toString();
        jLabel11.setText(combo);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        iGedung();
        try {
            Connection c = Koneksi.getkoneksi();
            Statement st = c.createStatement();

            String sql = "select * from detailbarang,ruangan where "
                    + "ruangan.kode_ruangan=detailbarang.ruanganfk and "
                    + "ruanganfk='" + jLabelKode.getText() + "'";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] o = new Object[11];
                o[0] = rs.getString("nama_ruangan");
                o[1] = rs.getString("kode_barang");
                o[2] = rs.getString("nama_barang");
                o[3] = rs.getString("tahun_pengadaan");
                o[4] = rs.getString("sfc");
                o[5] = rs.getString("jumlah");
                o[6] = rs.getString("kondisi_b");
                o[7] = rs.getString("kondisi_rr");
                o[8] = rs.getString("kondisi_rb");
                o[9] = rs.getString("kondisi_tt");
                o[10] = rs.getString("keterangan");

                model.addRow(o);
            }
            rs.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error tampil per ruangan\n" + e.getMessage());
        }
    }

    //
    public void keseluruhan() {
        jLabelKode.setText(null);
        jLabel9.setText("\"pilih ruangan\"");
        String combo = jComboRuangan.getSelectedItem().toString();
        jLabel11.setText(combo);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        iGedung();
        try {
            Connection c = Koneksi.getkoneksi();
            Statement st = c.createStatement();

            String sql = "select * from detailbarang,ruangan where "
                    + "detailbarang.ruanganfk=ruangan.kode_ruangan order by ruanganfk";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] o = new Object[11];
                o[0] = rs.getString("nama_ruangan");
                o[1] = rs.getString("kode_barang");
                o[2] = rs.getString("nama_barang");
                o[3] = rs.getString("tahun_pengadaan");
                o[4] = rs.getString("sfc");
                o[5] = rs.getString("jumlah");
                o[6] = rs.getString("kondisi_b");
                o[7] = rs.getString("kondisi_rr");
                o[8] = rs.getString("kondisi_rb");
                o[9] = rs.getString("kondisi_tt");
                o[10] = rs.getString("keterangan");

                model.addRow(o);
            }
            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error tampilkan keseluruhan\n" + e.getMessage());
        }
    }

    //
    @SuppressWarnings("unchecked")
    public void iComboR() {
        try {
            Connection c = Koneksi.getkoneksi();
            Statement st = c.createStatement();

            String sql = "select nama_ruangan from ruangan";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                jComboRuangan.addItem(rs.getString("nama_ruangan"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error insert data ke combobox\n" + e.getMessage());

            System.exit(0);
        }
    }

    //
    public void iGedung() {
        String combo = jComboRuangan.getSelectedItem().toString();
        try {

            Connection c = Koneksi.getkoneksi();
            Statement st = c.createStatement();
            String sql = "select gedung.nama_gedung from gedung,ruangan "
                    + "where gedung.kode_gedung=ruangan.gedungfk and "
                    + "ruangan.nama_ruangan ='" + combo + "'";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                jLabel9.setText(rs.getString("nama_gedung"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error tampilkan nama gedung\n" + e.getMessage());

        }

    }

    //
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonSimpan1;
    private javax.swing.JComboBox jComboRuangan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelKode;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextJumlah;
    private javax.swing.JTextField jTextKet;
    private javax.swing.JTextField jTextKode;
    private javax.swing.JTextField jTextKondisiB;
    private javax.swing.JTextField jTextKondisiRB;
    private javax.swing.JTextField jTextKondisiRR;
    private javax.swing.JTextField jTextKondisiTT;
    private javax.swing.JTextField jTextNamaBarang;
    private javax.swing.JTextField jTextSfc;
    private javax.swing.JTextField jTextTahunPengadaan;
    private javax.swing.JTable tabelbarang;
    // End of variables declaration//GEN-END:variables
}
